import './globals.css'
import "bootstrap/dist/css/bootstrap.min.css";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dev Test Exercise',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en" style={{backgroundColor:"#afffd0"}}>
      <body style={{backgroundColor:"#afffd0"}} className={inter.className}>{children}</body>
    </html>
  )
}
